Remove file_jpfid_idx creation on upgrade
Closes #591293
See http://bugs.bacula.org/view.php?id=1623

CREATE INDEX file_jpfid_idx on File (JobId, PathId, FilenameId);

And at http://bugs.debian.org/591293 [^] I received a bug report indicating that upgrades were failing with this message:

ERROR: relation "file_jpfid_idx" already exists

Now, investigating a bit...

In the 5.0.2 source tree, updatedb/update_postgresql_tables_7_to_8 contains this line:

create index file_jpfid_idx on file (jobid, pathid, filenameid);

In the 3.0.3 source tree, src/cats/make_postgresql_tables.in containts this line:

CREATE INDEX file_jpfid_idx on file (jobid, pathid, filenameid);

However, it was commented out in your distribution in 2.4.4 (but uncommented for Debian).

So it seems like people that installed fresh with 3.0.0 or later will
already have the index and thus the upgrade will fail. Those that
started with 2.4.4 will not have the index and will get it. But, of
course, those that started with 1.34 will also fail because it was
added for them with the upgrade to 1.35.